"""AI Studio entrypoint (Biz2 scaffolding).

Reads config.yaml, inspects available agents, and routes to lightweight workflow stubs.
Future work will replace the simple dispatcher with a LangGraph-style multi-agent runtime.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict

CONFIG_PATH = Path(__file__).parent / "config.yaml"
REPORTS_DIR = Path(__file__).parent / "reports"

WORKFLOW_SUMMARIES: Dict[str, str] = {
    "overview": "Prints charter summary and available scaffolding tasks.",
    "daily_digest": "Runs (placeholder) digest steps – see workflows/daily_digest.*",
    "prototype_loop": "Outlines PM→Architect→Engineer→Researcher→Marketer hand-off.",
}


def load_config():
    if not CONFIG_PATH.exists():
        raise FileNotFoundError(f"Missing config: {CONFIG_PATH}")
    with CONFIG_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def available_workflows():
    return sorted(WORKFLOW_SUMMARIES.keys())


def run_workflow(name: str, cfg: dict):
    if name not in WORKFLOW_SUMMARIES:
        raise ValueError(f"Unknown workflow '{name}'. Known: {', '.join(available_workflows())}")

    print(f"AI Studio – workflow '{name}' (stub)")
    print(f"Summary: {WORKFLOW_SUMMARIES[name]}")
    print(f"Agents configured: {', '.join(cfg.get('agents', {}).keys())}")
    print(f"Default LLM: {cfg.get('defaults', {}).get('llm')}")

    if name == "overview":
        _print_overview()
    elif name == "daily_digest":
        _print_daily_digest_stub()
    elif name == "prototype_loop":
        _print_prototype_loop_stub()

    _log_stub_run(name, cfg)


def _print_overview():
    print("Next steps:")
    print("  - Review projects/biz2/README.md")
    print("  - Tackle a box from projects/biz2/scaffolding_checklist.md")
    print("  - Update ai/studio/backlog.md with progress")


def _print_daily_digest_stub():
    print("Daily Digest stub:")
    print("  1. Collect 3-5 sources into memory/news/*.md with timestamps")
    print("  2. Summarize via local LLM → news_digest/<date>-digest.md")
    print("  3. Record follow-ups in ai/studio/backlog.md")


def _print_prototype_loop_stub():
    print("Prototype loop stub:")
    print("  PM -> Architect -> Engineer -> Researcher -> Marketer")
    print("  Use memory/experiments/<slug>.md for running notes")
    print("  Publish recap under reports/research/<slug>-recap.md")


def _log_stub_run(name: str, cfg: dict) -> None:
    """Write a lightweight decision log into reports/.

    This keeps a minimal trail of which workflow stub was run, with which
    agents and default LLM, so Biz2 has something to point to in reviews.
    """

    try:
        reports_root = REPORTS_DIR / "research"
        reports_root.mkdir(parents=True, exist_ok=True)
        out_path = reports_root / f"stub_run_{name}.md"
        agents = ", ".join(cfg.get("agents", {}).keys())
        default_llm = cfg.get("defaults", {}).get("llm")

        content = (
            "---\n"
            f"title: \"Biz2 stub run: {name}\"\n"
            "slug: \"biz2-stub-" + name + "\"\n"
            "status: \"draft\"\n"
            "tags: [\"biz2\", \"stub\"]\n"
            "---\n\n"
            f"Workflow: {name}\n\n"
            f"Agents: {agents}\n\n"
            f"Default LLM: {default_llm}\n\n"
            "This file is generated by ai/studio/main.py as a placeholder. "
            "Promote it into a full experiment recap using the templates in "
            "reports/research/ when the workflow stops being a stub.\n"
        )

        with out_path.open("w", encoding="utf-8") as f:
            f.write(content)
    except Exception:
        # Logging should never break the CLI; ignore errors silently.
        pass


def parse_args():
    parser = argparse.ArgumentParser(description="AI Studio workflow runner (scaffolding)")
    parser.add_argument(
        "--workflow",
        default="overview",
        choices=available_workflows(),
        help="Workflow stub to run",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    cfg = load_config()
    run_workflow(args.workflow, cfg)


if __name__ == "__main__":
    main()
