# Talos worker machine config template for prox-n100 (DHCP).
# Duplicate and adjust this config for talos-w-2 by changing `metadata.name`.
apiVersion: machineconfiguration.k8s.talos.dev/v1alpha1
kind: MachineConfig
metadata:
  name: talos-w-1
spec:
  machine:
    network:
      interfaces:
        - name: eth0
          dhcp: true
    install:
      disk: /dev/vda
  cluster:
    name: prox-n100
    endpoint: https://<CONTROL_PLANE_IP>:6443
    token: REPLACE_WITH_TALOS_BOOTSTRAP_TOKEN
    # Workers inherit the same bootstrap token as the control plane, but additional
    # nodeName/role fields will be populated by Talos once the kubelet joins.
