# Orchestrator v2 - Context Map
#
# This file maps stages to their relevant files and architecture sections.
# The Executor uses this to curate context for escalations.
#
# This file is treated as plumbing and should only be edited manually.

# Stage definitions
stages:
  vms:
    description: "Proxmox VM creation/configuration for Ubuntu Server + k3s nodes"
    command: "infrastructure/proxmox/provision_vms.sh"
    files:
      - infrastructure/proxmox/provision_vms.sh
      - config/clusters/prox-n100.yaml
      - config/env/prox-n100.env
    architecture_sections:
      - proxmox
      - kubernetes
    success_criteria:
      - "Ubuntu Server VMs created and running"
      - "VMs have the requested CPUs, RAM, and disk"
      - "VMs respond on their static IPs over vmbr0"

  k3s:
    description: "k3s bootstrap (control plane + workers)"
    command: "infrastructure/proxmox/cluster_bootstrap.sh k3s"
    files:
      - infrastructure/proxmox/provision_vms.sh
      - infrastructure/proxmox/cluster_bootstrap.sh
      - infrastructure/proxmox/check_cluster.sh
      - config/clusters/prox-n100.yaml
      - infrastructure/proxmox/k3s/kubeconfig
    architecture_sections:
      - kubernetes
      - flux
      - proxmox
    success_criteria:
      - "k3s control plane and agents installed"
      - "Nodes are Ready via kubeconfig"
      - "kubectl access to the cluster works"
    diagnostics:
      - "KUBECONFIG=infrastructure/proxmox/k3s/kubeconfig kubectl get nodes -o wide"
      - "KUBECONFIG=infrastructure/proxmox/k3s/kubeconfig kubectl cluster-info"
      - "KUBECONFIG=infrastructure/proxmox/k3s/kubeconfig kubectl -n kube-system get pods -o wide"

  infra:
    description: "Core platform infrastructure (Flux, Longhorn, NFS)"
    command: "infrastructure/proxmox/cluster_bootstrap.sh infra"
    files:
      - infrastructure/proxmox/cluster_bootstrap.sh
      - cluster/kubernetes/flux/flux-install.yaml
      - cluster/kubernetes/flux/gotk-sync.yaml
      - cluster/kubernetes/flux/gotk-components.yaml
      - cluster/kubernetes/platform/storage/longhorn/helmrelease.yaml
      - cluster/kubernetes/platform/storage/nfs-subdir/helmrelease.yaml
      - cluster/kubernetes/platform/kustomization.yaml
    architecture_sections:
      - flux
      - storage
      - kubernetes
    success_criteria:
      - "Flux controllers running in flux-system"
      - "Longhorn StorageClass available"
      - "NFS StorageClass available"
      - "Platform kustomizations reconciled"
    diagnostics:
      - "kubectl get pods -n flux-system"
      - "kubectl get kustomizations -A"
      - "kubectl get gitrepositories -A"
      - "kubectl get sc"
      - "kubectl get pods -n longhorn-system"

  apps:
    description: "Homelab applications (media, tools, games, demos)"
    command: "infrastructure/proxmox/cluster_bootstrap.sh apps"
    files:
      - infrastructure/proxmox/cluster_bootstrap.sh
      - cluster/kubernetes/flux/apps.yaml
      - cluster/kubernetes/apps/
    architecture_sections:
      - apps
      - flux
    success_criteria:
      - "Apps kustomization reconciled"
      - "Core apps running"
    diagnostics:
      - "kubectl get kustomizations -A"
      - "kubectl get pods -A | grep -v kube-system | grep -v flux-system"
      - "kubectl get pvc -A"

  ingress:
    description: "Ingress, Cloudflare tunnel, external-dns"
    command: "infrastructure/proxmox/cluster_bootstrap.sh apps"
    files:
      - cluster/kubernetes/platform/ingress/ingress-nginx/helmrelease.yaml
      - cluster/kubernetes/platform/ingress/cloudflared/deployment.yaml
      - cluster/kubernetes/platform/ingress/kustomization.yaml
    architecture_sections:
      - ingress
      - cloudflare
      - dns
    success_criteria:
      - "ingress-nginx controller running"
      - "cloudflared tunnel connected"
      - "external-dns syncing records"
    diagnostics:
      - "kubectl get pods -n ingress-nginx"
      - "kubectl get pods -n cloudflared"
      - "kubectl get ingress -A"
      - "kubectl logs -n cloudflared deploy/cloudflared --tail=50"

  obs:
    description: "Observability stack (Prometheus, Loki, Grafana, OTel)"
    command: "infrastructure/proxmox/cluster_bootstrap.sh apps"
    files:
      - cluster/kubernetes/platform/monitoring/grafana/helmrelease.yaml
      - cluster/kubernetes/platform/monitoring/metrics-server/helmrelease.yaml
      - cluster/kubernetes/platform/monitoring/alertmanager/helmrelease.yaml
      - cluster/kubernetes/platform/monitoring/kustomization.yaml
    architecture_sections:
      - monitoring
      - observability
    success_criteria:
      - "Prometheus scraping metrics"
      - "Grafana accessible"
      - "Loki collecting logs"
    diagnostics:
      - "kubectl get pods -n monitoring"
      - "kubectl get servicemonitors -A"
      - "kubectl logs -n monitoring deploy/grafana --tail=50"

# Protected files - AI must not modify these
protected_files:
  - ai/master_memo.md
  - ai/context_map.yaml
  - ai/bootstrap_loop.sh
  - ai/state/errors.json
  - ai/state/stage_status.json
  - infrastructure/proxmox/wipe_proxmox.sh

# Architecture sections referenced in stage mappings
# These map to sections in ai/master_memo.md
  architecture_section_keywords:
  proxmox:
    - "Proxmox"
    - "VM"
    - "virtualization"
  k3s:
    - "Ubuntu Server"
    - "k3s"
    - "control plane"
    - "worker"
  kubernetes:
    - "Kubernetes"
    - "kubectl"
    - "kubeconfig"
  flux:
    - "Flux"
    - "GitOps"
    - "Kustomization"
    - "HelmRelease"
  storage:
    - "Longhorn"
    - "NFS"
    - "StorageClass"
    - "PVC"
  ingress:
    - "ingress-nginx"
    - "Ingress"
    - "LoadBalancer"
  cloudflare:
    - "Cloudflare"
    - "tunnel"
    - "cloudflared"
  dns:
    - "external-dns"
    - "DNS"
  apps:
    - "applications"
    - "media"
    - "tools"
  monitoring:
    - "Prometheus"
    - "Grafana"
    - "metrics"
  observability:
    - "Loki"
    - "logging"
    - "OpenTelemetry"
    - "traces"
